### ISSUE TITLE
How to determinate parameters in ex_undistort_rectify.txt file?

### ISSUE THREAD

**Issue by RegisWang** [BKhomutenko/visgeom#1]
Hi, 
your work is brillante, but there is a problem in my experiment. I don't know how to determinate %u0 %v0 %f and %Rotation Vector in the ex_undistort_rectify.txt. In your example, I found these parameters is suitable for all images, can you tell me how to get them?

Thanks.

**Comment by BKhomutenko** [comment]
Hello and thank you.
%u0 %v0 %f and %Rotation Vector are just parameters for a virtual camera. In fact here is what's happening, you reconstruct in 3D every pixel of your virtual camera, rotate them and project them on the real image using the calibrated model. Then you take the image brightness values at the points and put them into you virtual image.
So indeed any parameters will work out. They also define the rectified image size. So you choose them according to the application. Try different values to see the effect.

Regards.
